import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { getAvailableReports } from "@reportplatform/reports";
import type { ReportRun } from "@reportplatform/shared";

import { markReportRunFailed, markReportRunSucceeded } from "./report-runs.repository.js";
import { storageDir } from "./config.js";

function buildStubContent(run: ReportRun): string {
  const reportDetails = getAvailableReports().find((report) => report.key === run.reportKey);
  const title = reportDetails?.name ?? run.reportKey;

  return [
    `Report: ${title}`,
    `Run ID: ${run.id}`,
    `Format: ${run.format}`,
    `Created At: ${run.createdAt}`,
    `Params: ${JSON.stringify(run.params)}`,
    "",
    "Generated by worker stub for MVP demo.",
  ].join("\n");
}

export async function processReportRun(run: ReportRun): Promise<void> {
  const report = getAvailableReports().find((entry) => entry.key === run.reportKey);
  if (!report) {
    await markReportRunFailed(run.id, `Unknown report key: ${run.reportKey}`);
    return;
  }

  if (!report.formats.includes(run.format)) {
    await markReportRunFailed(
      run.id,
      `Format ${run.format} is not supported by report ${run.reportKey}`,
    );
    return;
  }

  const fileExtension = run.format === "pdf" ? "pdf" : "xlsx";
  const relativeFilePath = `${run.id}.${fileExtension}`;
  const targetFilePath = resolve(storageDir, relativeFilePath);
  const fileName = `${run.reportKey}-${run.id}.${fileExtension}`;
  const stubContent = buildStubContent(run);

  await mkdir(storageDir, { recursive: true });
  await writeFile(targetFilePath, stubContent, "utf8");
  await markReportRunSucceeded(run.id, relativeFilePath, fileName);
}
