import type { ReportRun } from "@reportplatform/shared";

export function buildStubReportContent(reportName: string, run: ReportRun): string {
  return [
    `Report: ${reportName}`,
    `Run ID: ${run.id}`,
    `Format: ${run.format}`,
    `Created At: ${run.createdAt}`,
    `Params: ${JSON.stringify(run.params)}`,
    "",
    "Generated by report handler stub for MVP demo.",
  ].join("\n");
}
